// require theme/jquery-2.1.0.min
// require theme/bootstrap.min.js
// require theme/rs-plugin/initialize
// require theme/owl.carousel.min
// require theme/isotope/initialize
// require theme/jquery.raty.min
// require theme/jquery.appear
// require theme/jquery.simple-text-rotator.min
// require theme/jquery.magnific-popup.min
// require theme/ion.rangeSlider.min
// require theme/stellar.min
// require theme/retina.min
// require theme/sticky.min
// require theme/script